// <auto-generated />
using System;
using DailyWork.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DailyWork.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714184426_AddCalendarForecastJsonToWorkSessions")]
    partial class AddCalendarForecastJsonToWorkSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DailyWork.Api.Entities.ReadWatchItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("WeekConsumed")
                        .HasColumnType("date");

                    b.Property<bool?>("WorthSharing")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("IsActive");

                    b.HasIndex("WeekConsumed");

                    b.ToTable("ReadWatchItems");
                });

            modelBuilder.Entity("DailyWork.Api.Entities.ScratchPad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("ScratchPads");
                });

            modelBuilder.Entity("DailyWork.Api.Entities.UpdateComm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Date", "CommType")
                        .IsUnique();

                    b.ToTable("UpdateComms", (string)null);

                    b.HasDiscriminator<int>("CommType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DailyWork.Api.Entities.WorkItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("OriginalDate")
                        .HasColumnType("date");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("TimesMoved")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeekOf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("WeekOf");

                    b.HasIndex("Date", "Category", "SortOrder");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("DailyWork.Api.Entities.WorkSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CalendarForecastJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClockedInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ClockedOutAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("WorkSessions");
                });

            modelBuilder.Entity("DailyWork.Api.Entities.DailyStandupComm", b =>
                {
                    b.HasBaseType("DailyWork.Api.Entities.UpdateComm");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("DailyWork.Api.Entities.WeeklySummaryComm", b =>
                {
                    b.HasBaseType("DailyWork.Api.Entities.UpdateComm");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("DailyWork.Api.Entities.WeeklyUpdateComm", b =>
                {
                    b.HasBaseType("DailyWork.Api.Entities.UpdateComm");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("DailyWork.Api.Entities.WorkSession", b =>
                {
                    b.OwnsOne("DailyWork.Api.Entities.WorkSessionReflections", "Reflections", b1 =>
                        {
                            b1.Property<int>("WorkSessionId");

                            b1.Property<string>("ValueAdds");

                            b1.Property<string>("Whines");

                            b1.Property<string>("Wins");

                            b1.HasKey("WorkSessionId");

                            b1.ToTable("WorkSessions");

                            b1
                                .ToJson("Reflections")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkSessionId");
                        });

                    b.Navigation("Reflections");
                });
#pragma warning restore 612, 618
        }
    }
}
